controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

repository-cache:
    path: /repository-cache
    controller: App\Controller\RepositoryCacheController
    methods: GET